---
kind: pipeline
name: test

steps:
- name: test
  image: python
  commands:
  - echo "Hi - let's do a test"
  - python -m unittest tests.test -v

trigger:
  branch:
    include:
    - master
    - dev
  event:
    - pull_request

---
kind: pipeline

steps:
  - name: tag
    image: python
    commands:
    - echo "Tag acknowledged"
  
trigger:
  event:
    - tag

